In [1]:
import pandas as pd

df = pd.read_csv('./data/OHE.csv')

In [16]:
from sklearn.model_selection import train_test_split

In [2]:
df

,Overall AQI Value,Ozone,PM25,CO,PM10,NO2,AQI category,Date,Month,Year,...,MD,MI,MN,NC,NY,OH,OR,PA,TX,VA
0,30,27,30,6,8,21,Good,12,26,2023,...,0,0,0,0,0,0,0,0,0,1
1,30,30,29,9,8,21,Good,9,12,2023,...,0,1,0,0,0,0,0,0,0,0
2,84,84,54,6,23,33,Moderate,9,19,2023,...,0,0,0,0,0,0,0,0,0,0
3,58,38,58,8,14,25,Moderate,5,5,2023,...,0,0,0,0,0,0,0,1,0,0
4,48,48,23,3,11,18,Good,2,22,2023,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6489,49,49,46,6,10,15,Good,9,4,2023,...,0,0,0,1,0,0,0,0,0,0
6490,58,58,36,5,14,23,Moderate,6,3,2023,...,0,0,0,0,0,0,0,0,0,0
6491,67,67,25,7,36,49,Moderate,3,31,2023,...,0,0,0,0,0,0,0,0,0,0
6492,45,45,41,5,19,35,Good,5,18,2023,...,0,0,0,0,1,0,0,0,0,0
6493,26,26,14,3,5,6,Good,10,14,2023,...,0,0,0,0,0,1,0,0,0,0

In [13]:
hazardous_idx = df[df['AQI category'] == 'Hazardous'].index
df.drop(hazardous_idx, inplace = True)

In [15]:
df['AQI category'].value_counts()

AQI category
Good                              3122
Moderate                          2843
Unhealthy for Sensitive Groups     413
Unhealthy                          103
Very Unhealthy                      12
Name: count, dtype: int64

In [18]:
#seperate features and target
Y = df['AQI category']
X = df.drop(['AQI category'], axis = 'columns')

In [21]:
#split train-test dataset
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [23]:
# y_val, x_val to csv files
x_train.to_csv('./data/x_train_dataset.csv', index = False)
y_train.to_csv('./data/y_train_dataset.csv', index = False)
x_test.to_csv('./data/x_test_dataset.csv', index = False)
y_test.to_csv('./data/y_test_dataset.csv', index = False)